name: storage_manager
description: FireStorage & DevicePersistor Manager facilitates quick implementation in your app
version: 0.1.3
homepage: https://github.com/SirLegui/storage_manager

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^10.2.0
  flash: ^2.0.3
  image_picker: ^0.8.4+5
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
